### PR TITLE
added ascii only filepath option for windows

### PR DESCRIPTION
**Pull request by septag**
Added an option *CR_WINDOWS_UTF8_PATHS* to disable utf8 path implementation for windows and use ascii paths only. mainly for performance reasons.
also added WIN32_LEAN_AND_MEAN for faster compile times

I also noticed that *cr_copy* posix implementation is pretty slow and there's a much robust method for copying files in unix, I'll submit another PR for that.

### CODE REVIEW

**Comment by fungos** [comment]
Do you have any measurement about the performance impact of using utf8/wstrings here? Also I dislike the amount of code duplicated this introduces without further details on performance. This would also benefit of another test case using each of the two variants.

One way out that can work for us both would be to not duplicate these but to find a way using macros wrapping wstring / string and maybe manipulating windows.h to use the correct W or A version based on this.

**Comment by septag** [comment]
I just profiled ```cr_utf8_to_wstring``` on my 2012 i7 machine (Release build + vc2015). it takes about 3000ns for one call and 0.08 ms for 100 samples.

Yes we can use macros for windows functions. but it takes some more for wrapping up std::string and std::wstring and the conversion code. I can do that approach too if you prefer.

About the PR, yes I was actually was hesitating to submit this PR because it was very personal. For me, I hate utf8 conversions to wchar in windows. they all should be managed by the OS itself internally. And I almost never use them in my file paths. So in my fork, I use the char versions. and because the frequency of the cr_utf7_to_wstring is pretty high, if you have for example 100 plugins that updates every frame, you get lots of utf8 conversions and wstring allocations. But after all it's just neat picking and personal preference

If you don't like it, it's ok, I have more PRs waiting to be submitted and discussed ;)

**Comment by fungos** [comment]
Yeah, I hate this situation on windows too, but this is a windows issue in the end. Now, being ascii-centric is not much friendly, and I mostly hate ascii-only software. :)

As wstring and string have the same api, you can just typedef something to one or another and it will be good to go.

For the conversion function, there can be a define that will be kind of no-op in the ascii version. With this, we can have both options without introducing much noise and giving the choice to the user.

**Comment by septag** [comment]
Danny,
I wanted to propose another thing that I've just found. and I think I may have found a potential bug too (which is fixed in latest PR commit)

In MSVC if you can choose between unicode and multi-byte character set in build settings. unicode mode defines ```UNICODE``` preprocessor, which changes all the win32 API to unicode versions.
So, we can use this to change how cr.h works with paths too. if the user sets to unicode character set, all the functions translate paths from utf8 to unicode and use the standard APIs (CopyFile, DeleteFile, etc..)

And also I just found out that the cr.h is inconsistent in it's API usage. Some parts of code like ```cr_pdb_replace```, ```cr_pdb_process``` and ```cr_so_load``` used macro win api like ```CreateFile``` and even ```CopyFile``` (and also doesn't use the utf8 paths). And if we change the build to unicode charset, we will get build errors.

This is actually the confusion I want to avoid on windows API, and use utf8 strings specifically for special cases like text and localization, ...
Now with the current PR, it's up to user which windows API to use and _cr_ will assume the paths are utf8 or ascii based on what charset is set for the build. I think it's kind of a more standard way of handling this ?

**Comment by fungos** [comment]
This is excellent, thanks a lot for cleaning up this!

**Pull request merged**
